language: node_js
services:
  - mongodb
  - redis-server
node_js:
  - 9
env:
  global:
    # remove this when using docker
    - REDEEMER_URL=http://localhost:3333
    - MONGODB_URI=localhost/test
    - NODE_ENV=development
    - REDIS_URL=redis://localhost:6379
    - BAT_LEDGER_SERVER=http://localhost:3001
    - BAT_EYESHADE_SERVER=http://localhost:3002
    - BAT_HELPER_SERVER=http://localhost:3004
    - BAT_GRANT_SERVER=http://localhost:3333
  - FRESH_DEPS=true
cache:
  directories:
    - $HOME/.npm
before_install:
  - openssl aes-256-cbc -K $encrypted_8bcd13e0bfb0_key -iv $encrypted_8bcd13e0bfb0_iv -in .env.enc -out .env -d
  - npm i --global npm@5.8.0
  - npm --version
install: |
  if [[ ${FRESH_DEPS} == "true" ]]; then
    npm i --no-shrinkwrap --prefer-online;
  else
    npm ci;
    checksum=$(md5sum package-lock.json);
    npm i --package-lock-only;
    if ! echo ${checksum} | md5sum --quiet -c -; then
      echo "package-lock.json was modified unexpectedly. Please rebuild it using npm@$(npm -v) and commit the changes.";
      exit 1;
    fi
  fi
before_script:
  - npm run lint
  - npm run redis-flush
  - npm run start-ledger & npm run start-ledger-worker &
  - sleep 10
  - npm run create-promotion
after_success: npx codecov --file=./coverage/lcov.info
