version: "2.1"

services:
  captcha-web:
    container_name: captcha-web
    image: bat-captcha:latest
    ports:
      - "3334:3334"
    environment:
      - TOKEN_LIST
      - "ALLOW_DEBUG_APK=1"
      - "IGNORE_APK_DIGEST=1"
    networks:
      - ledger
  ledger-web:
    environment:
      - "CAPTCHA_URL=${CAPTCHA_URL-http://captcha-web:3334}"
