# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - prod
      - dev
  pull_request:
    branches:
      - master
      - prod

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          # Set always-auth in npmrc
          always-auth: true
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 12.x
          # Set this option if you want the action to check for the latest available version that satisfies the version spec
          check-latest: true

      - name: Docker Compose Install
        uses: isbang/compose-action@v0.1.1

      # Runs a single command using the runners shell
      - name: Run security checks (audit + lint)
        run: npm run security
      
      # Runs a set of commands using the runners shell
      - name: Stand up Postgres
        run: |
          docker-compose up -d eyeshade-postgres
          docker-compose up -d wallet-migration-postgres
          sleep 3

      - name: Migrate DBs
        run: npm run docker-migrate-up
      - name: Bring Up App Containers
        run: npm run docker-up-detached
      - name: Print Checks
        run: |
          sleep 20
          docker ps

      - name: Test
        run: npm run docker-test
      - name: Check Migrating Down
        run: npm run docker-migrate-down-all

      - name: Coverage
        run: npm run coverage
      - name: Submit Code Coverage
        run: npx codecov --file=./coverage/lcov.info
